version: '3'
services:
    redis-test:
      image: "redis"
      restart: always
      container_name: "redis-test"
      ports:
        - "15001:6379"
      volumes:
        - /Users/pengze/Desktop/configCollection:/data
      command: ["redis-server","--requirepass","123456"]  
        

      